name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build service
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - name: Install yarn globally
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Setting up dependency Cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Installing Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --immutable

      - name: Build service
        run: yarn build
